### PR TITLE
Fix indirect array access

### LINKED ISSUE #61: Create a method to create an instance of ArrayAccessFormState from an existing form state object
Context: https://drupal.slack.com/archives/C05BT6LALUR/p1697740424037859

Field widgets will need an instance of `ArrayAccessFormState`. Retrofit will need to decorate the original form state before invoking callbacks.

### LINKED ISSUE #69: D7 form elements need decorated $form_state for validation
Having a problem with form elements from D7 modules because the FormState class does not allow array access.

### PR DESCRIPTION
**Pull request by darrenoh**
fixes #69 
fixes #61

### CODE REVIEW

**Comment by darrenoh** [comment]
Closes #69

**Comment by darrenoh** [comment]
Closes #61

**Review by mglaman — APPROVED** [review]
Thank you!

**Comment by darrenoh** [comment]
Found some errors in testing.

File: src/Controller/HtmlFormController.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+        $form_state = new ArrayAccessFormState();
+        $request->attributes->set('form', []);
+        $request->attributes->set('form_state', $form_state);
+        $args = $this->argumentResolver->getArguments($request, [$form_object, 'buildForm']);
+        $request->attributes->remove('form');
+        $request->attributes->remove('form_state');
+        unset($args[0], $args[1]);
+        $form_state->addBuildInfo('args', array_values($args));
+        return $this->formBuilder->buildForm($form_object, $form_state);
+    }
```
Comment (mglaman) [inline src/Controller/HtmlFormController.php:30]: This recreates a lot of logic. My first thought is: can't we decorate the form builder to handle the form state in `\Drupal\Core\Form\FormBuilderInterface::buildForm`.

File: src/Entity/EntityFormBuilder.php [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+     * @param mixed[] $form_state_additions
+     * @return mixed[]
+     */
+    public function getForm(EntityInterface $entity, $operation = 'default', array $form_state_additions = []): array
+    {
+        $form_object = $this->entityTypeManager->getFormObject($entity->getEntityTypeId(), $operation);
+        $form_object->setEntity($entity);
+        $form_state = (new ArrayAccessFormState())->setFormState($form_state_additions);
+        return $this->formBuilder->buildForm($form_object, $form_state);
+    }
```
Comment (mglaman) [inline src/Entity/EntityFormBuilder.php:24]: This invokes `\Drupal\Core\Form\FormBuilder::buildForm`, so can we delegate the form state decoration there? It seems like it would reduce the amount of times we need to try and handle this.

File: src/Entity/HtmlEntityFormController.php [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+        $form_object = $this->getFormObject($route_match, $form_arg);
+        $form_state = new ArrayAccessFormState();
+        $request->attributes->set('form', []);
+        $request->attributes->set('form_state', $form_state);
+        $args = $this->argumentResolver->getArguments($request, [$form_object, 'buildForm']);
+        $request->attributes->remove('form');
+        $request->attributes->remove('form_state');
+        unset($args[0], $args[1]);
+        $form_state->addBuildInfo('args', array_values($args));
+        return $this->formBuilder->buildForm($form_object, $form_state);
```
Comment (mglaman) [inline src/Entity/HtmlEntityFormController.php:29]: Again, calling `buildForm` so that seems like the place to fix it

File: src/Form/FormBuilder.php [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+     * @return mixed[]
+     */
+    public function getForm(mixed $form_arg): array
+    {
+        $form_state = new ArrayAccessFormState();
+        $args = func_get_args();
+        array_shift($args);
+        $form_state->addBuildInfo('args', $args);
+        return $this->buildForm($form_arg, $form_state);
+    }
```
Comment (mglaman) [inline src/Form/FormBuilder.php:23]: Okay, we are decorating the form builder. Can we override `buildForm` instead?

```php
public function buildForm($form_arg, FormStateInterface &$form_state) 
{
	$form_state = (new ArrayAccessFormState())->setFormState($form_state_additions);
	return parent::buildForm($form_arg, $form_state);
}
```

**Comment by darrenoh** [comment]
Form state decoration did not work because it did not allow array access to private properties as expected by Drupal 7 modules. For that reason, it was necessary to replace FormState with ArrayAccessFormState at the point of creation.

File: src/Form/FormBuilder.php (hunk 4 above)
Comment (darrenoh) [reply src/Form/FormBuilder.php:23]: Possibly this:
```
public function buildForm($form_arg, FormStateInterface &$form_state) 
{
	$form_state = (new ArrayAccessFormState())->setFormState($form_state->getCacheableArray());
	return parent::buildForm($form_arg, $form_state);
}
```

Comment (darrenoh) [reply src/Form/FormBuilder.php:23]: Doesn't work. If a property doesn't exist the value gets added to the storage property.

Comment (mglaman) [reply src/Form/FormBuilder.php:23]: Okay, so what about the pattern here; 

```
    $original_form_state = $form_state;
    $form_state = new ArrayAccessFormState();
    foreach ($original_form_state as $offset => $value) {
        $form_state[$offset] = $value;
    }
```

Could that be used inside of `buildForm`

Comment (darrenoh) [reply src/Form/FormBuilder.php]: Something close to that worked.

File: src/Form/ArrayAccessFormState.php [hunk 5]
```diff
@@ -5,28 +5,54 @@
...
 
 final class ArrayAccessFormState extends FormState implements \ArrayAccess
 {
     public function offsetExists(mixed $offset): bool
     {
-        return match ($offset) {
-            'values' => true,
-            default => isset($this->$offset),
-        };
+        return isset($this->$offset);
```
Comment (mglaman) [inline src/Form/ArrayAccessFormState.php:14]: :D smart.

**Review by mglaman — APPROVED** [review]

**Comment by mglaman** [comment]
@darrenoh thanks so much for working through this with me!
